"use server"

// This is a simple server action that simulates getting an answer from a backend
export async function getAnswer(question: string): Promise<string> {
  // Simulate network delay
  await new Promise((resolve) => setTimeout(resolve, 1500))

  // In a real application, you would call your AI service, database, or API here
  // For demonstration, we'll return a simple response based on the question

  const questionLower = question.toLowerCase()

  if (questionLower.includes("hello") || questionLower.includes("hi")) {
    return "Hello! How can I help you today?"
  }

  if (questionLower.includes("weather")) {
    return "I cannot provide real-time weather information. Please check a weather service for accurate forecasts."
  }

  if (questionLower.includes("name")) {
    return "I am an AI assistant designed to answer your questions."
  }

  if (questionLower.includes("time") || questionLower.includes("date")) {
    return `The current server time is ${new Date().toLocaleString()}.`
  }

  // Default response
  return `Thank you for asking: "${question}"\n\nThis is a simulated answer. In a real application, this would be generated by your backend service, AI model, or retrieved from a database.`
}
